### ISSUE TITLE
请问该插件能否兼容v1？

### ISSUE THREAD

**Issue by wosiwq** [GWYOG/HoshinoBotTimelinePlugin#1]
如果能的话 能否告知修改哪些行的代码 谢谢

**Comment by GWYOG** [comment]
不好意思..不知道为什么这个仓库我的watch没了，一直没收到提醒才看到这个issue。
我没用过Hoshino v1，所以我也不太清楚要改哪些，不过这个插件本身使用hoshino的东西不多，如果想兼容v1应该不需要改太多地方。
但我暂时没有兼容v1的想法，这个插件本质上是我想做的三个插件的其中一个：录入可以用的轴的插件、录入全公会box的插件、基于轴和box的自动排刀。目前只剩自动排刀还没做，但出于工程量考虑，都兼容v1可能有点难...
这个插件本质和腾讯在线文档功能类似，如果装不了也可以用腾讯在线文档管理轴。
