### ISSUE TITLE
C阶段适配

### ISSUE THREAD

**Issue by wosiwq** [GWYOG/HoshinoBotTimelinePlugin#2]
国服从这期开始出现了C阶段 但是本插件仅能储存AB阶段的轴 能否适配增加一个阶段呢 麻烦了

**Comment by GWYOG** [comment]
其实是支持C阶段的..只是当时说明里我只写了A和B.   XD
比如：`录入轴 C3 110W yls7ub轴 xxxx `，`查看轴C`，`查看轴C3`
晚点我再更新下插件的说明

**Comment by wosiwq** [comment]
是我的问题 没去看过实现方式（（（
